[geometry] Add new geometry::DrakeVisualizer system
RobotLocomotion/drake pull request #14247
Opened 2020-10-23 20:32 UTC by SeanCurtis-TRI

A new leaf system that supplants the old `geometry::ConnectDrakeVisualizer` functionality. The introduction of this `System` improves Drake in several ways.

1. It provides a visualizer example that make use of the `QueryObject` and `SceneGraphInspector` public API (the old version exercised internal code).
2. It has the ability to update the visualization based on changes to the geometry.
3. It is a single system (rather than an entire diagram).
4. It frees `SceneGraph` to remove the out-dated `PoseBundle` output port that is currently used to visualize to `drake_visualizer`.

This
  - Includes the C++ and python versions of the new `System`.
  - Updates `examples/scene_graph` to make use `DrakeVisualizer`.
  - Adds upgraded unit tests over those for the old interface.
  - It also tweaks `GeometryVersion` to allow for default construction of versions so that objects can default construct a `GeometryVersion` member.
  - Extends the API for `SceneGraphInspector` with some helpful methods.

relates #13597

2020-10-23 20:36 UTC, SeanCurtis-TRI reviewed
+@ericcousineau-tri for feature review.

This is quite large (~1300 lines). The core files (.h, .cc, _test.cc) account for 1130 lines, so, it's jumbo-ness is probably inescapable. Feel free to take your time and defer it until after you've  recovered from Monday's platform review. But since you've tackled the same problem, exercising the same public API, I figured you'd be imminently qualified to weigh in. Note: this exploits the newly added `GeometryVersion` to allow the visualizer to update itself based on upstream changes.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247#-:-MKM9kaNCzXAQDn0p4QI:bsxox0k)* status: LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2020-10-26 13:39 UTC, SeanCurtis-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[geometry/test/drake_visualizer_test.cc, line 169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MK_6RV9-aXdn6bFwtiA:-MK_6RVA-Xpe2nkhyAIq:b7qw2rx) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/test/drake_visualizer_test.cc#L169)):*
> ```cpp
>   }
> 
>   /* Collection of data for reporting what is waiting int the LCM queue.  */
> ```

nit s/int/in


<!-- Sent from Reviewable.io -->

2020-10-27 13:57 UTC, EricCousineau-TRI reviewed
Checkpoint!

> Reviewed 9 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247#-:-MKeLP6Z1KshU-PacdtT:by96gd0)* status: 10 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[bindings/pydrake/test/geometry_test.py, line 226 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeGZIq9VV97ieB0BUm:-MKeGZIrCJfNY5XRzEVQ:bsizr1l) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/bindings/pydrake/test/geometry_test.py#L226)):*
> ```Python
>         lcm = DrakeLcm()
>         role = mut.Role.kIllustration
>         test_prefix = "TEST_PREFIX_"
> ```

nit This is unused?
___
*[geometry/drake_visualizer.h, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeGv891iR9qhOQ0A-w:-MKeGv891iR9qhOQ0A-x:b-1m91jv) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L21)):*
> ```
> d
> ```
___
*[geometry/drake_visualizer.h, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHHId9y9bXTdO2lOt:-MKeHHId9y9bXTdO2lOu:bew6x0s) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L102)):*
> ```objc
>  <h3>Thread safety</h3>
> 
>  Using this system in multiple, simultaneous threads can easily lead to
> ```

nit This seems kinda obvious?

I mean, you can have the same condition without threading, e.g. two separate systems publishing to the same subscriber?
___
*[geometry/drake_visualizer.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeIFXt-7vIzXYSwF20:-MKeIFXt-7vIzXYSwF21:b-udgl42) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L170)):*
> ```cpp
>   }
> 
>   // TODO(SeanCurtis-TRI) The down side of doing everything in an unrestricted
> ```

nit I don't understand what I'm supposed to gain from this comment?

An unrestricted update seems inappropriate for this system? (e.g. `mutable` seems most appropriate, given discussion in #13776)
___
*[geometry/drake_visualizer.cc, line 194 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeIdgO-tLoA6bAbfv2:-MKeIdgO-tLoA6bAbfv3:b-r1lzph) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L194)):*
> ```cpp
> void DrakeVisualizer::SendGeometryMessage(
>     const Context<double>& context) const {
>   // TODO(SeanCurtis-TRI) When GeometryVersion is available, query the version
> ```

nit This TODO seems stale now?
___
*[geometry/drake_visualizer.cc, line 195 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeIbR59LsqwB51uwKb:-MKeIbR59LsqwB51uwKc:bb6bd0u) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L195)):*
> ```cpp
>     const Context<double>& context) const {
>   // TODO(SeanCurtis-TRI) When GeometryVersion is available, query the version
>   //  availble via QueryObject::inspector() to determine if it matches this
> ```

nit spelling "availble"
___
*[geometry/drake_visualizer.cc, line 215 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHfCh5inLpvFul66i:-MKeHfCh5inLpvFul66j:b-2tzjyp) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L215)):*
> ```cpp
> }
> 
> void DrakeVisualizer::SendLoadMessage(const Context<double>& context) const {
> ```

FYI @sammy-tri We had spoken about this before - publicly exposing the message translation so that we could do multi-robot visualization. (#12702)
___
*[geometry/drake_visualizer.cc, line 285 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHofPDJcO6YMAZMjR:-MKeHofPDJcO6YMAZMjS:b-g5v9xa) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L285)):*
> ```cpp
>   }
> 
>   lcm::Publish(lcm_, "DRAKE_VIEWER_LOAD_ROBOT", message, context.get_time());
> ```

nit This channel is part of the public API (e.g. consumers should expect exactly this channel).

Can you hoist this to a public constant, e.g. `DrakeVisualizer::kLoadMessageChannel`?
___
*[geometry/drake_visualizer.cc, line 326 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHylz7drNhrRtIqsU:-MKeHylz7drNhrRtIqsV:b-4wuyzk) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L326)):*
> ```cpp
>   }
> 
>   lcm::Publish(lcm_, "DRAKE_VIEWER_DRAW", message, context.get_time());
> ```

nit This channel is part of the public API (e.g. consumers should expect exactly this channel).

Can you hoist this to a public constant, e.g. `DrakeVisualizer::kDrawMessageChannel`?
___
*[geometry/test/drake_visualizer_test.cc, line 171 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeJBjJ4pzbk9DTGnrN:-MKeJBjJ4pzbk9DTGnrO:bp6z5sc) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/test/drake_visualizer_test.cc#L171)):*
> ```cpp
>   /* Collection of data for reporting what is waiting int the LCM queue.  */
>   struct MessageResults {
>     int num_load;
> ```

nit All of these are POD (I believe including the LCM types?) and should be default initialized.
___
*[geometry/test/drake_visualizer_test.cc, line 234 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeJQRF6oLSFWEkRy7D:-MKeJQRF6oLSFWEkRy7E:b-75ywhf) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/test/drake_visualizer_test.cc#L234)):*
> ```cpp
> 
> /* Confirms that the visualizer publishes at the specified period.  */
> TEST_F(DrakeVisualizerTest, PublishPeriod) {
> ```

BTW Hm... This smells like it's testing the systems framework that already has its own unittest?

It would be nice if this could be simplified? (e.g. just ensure you have the periodic publish you want?)


<!-- Sent from Reviewable.io -->

2020-10-27 14:01 UTC, EricCousineau-TRI commented
Writing issue numbers in GitHub for its xref magic:
- Use QueryObject properly for visualization: #10482
- Multiple posture viz: #12702 (#10780)

2020-10-27 14:02 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: 10 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[geometry/drake_visualizer.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeMPN30g_4puGrKKeG:-MKeMPN30g_4puGrKKeH:bfi83xh) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L19)):*
> ```objc
> namespace geometry {
> 
> /* TODO(SeanCurtis-TRI): Here's the stuff that needs to happen:
> ```

Can this TODO be resolved in this PR?

i.e. can you basically just make an overload for `ConnectDrakeVisualizer` that uses `DrakeVisualizerParams`?
___
*[geometry/drake_visualizer.h, line 21 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeGv891iR9qhOQ0A-w:-MKeMOPlCOxe9Dp2duNl:bkyjb5r) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L21)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

> ```
> d
> ```

</blockquote></details>

OK Oops!


<!-- Sent from Reviewable.io -->

2020-10-27 16:13 UTC, SeanCurtis-TRI reviewed
Addressed comments. Some may not be to your liking.  :)  PTAL

I also realized I hadn't bound the new SGInspector code, and saw some binding inconsistencies that I corrected. Quick question:

In the SceneGraphInspector::Get*Properties, in C++ the parameter was `id` and the python parameter was `geometry_id`. I considered this to be a defect. I opted to change the C++ to `geometry_id` because I felt the other way around would break a mountain of python code (and I wasn't sure how to deprecate). In a vacuum, I prefer the more terse `id` as there is only one `id` parameter to the method. Was there a slick way I could've brought the binding in line with the C++? Or should I have ignored the disparity in parameter names?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247#-:-MKelYDs1dt3SV4HadRa:b-py48lt)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/test/geometry_test.py, line 226 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeGZIq9VV97ieB0BUm:-MKefDY40rE8FOVHAEtX:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/bindings/pydrake/test/geometry_test.py#L226)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This is unused?
</blockquote></details>

Done
___
*[geometry/drake_visualizer.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeMPN30g_4puGrKKeG:-MKefgZW5CwC1AiB2EAp:bn46j5r) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can this TODO be resolved in this PR?

i.e. can you basically just make an overload for `ConnectDrakeVisualizer` that uses `DrakeVisualizerParams`?
</blockquote></details>

The PR is already huge, I'd rather defer that to the second check box in the linked issue (#13597). Essentially, I think `ConnectDrakeVisualizer` will essentially play that role (for reasons of backwards compatibility).
___
*[geometry/drake_visualizer.h, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHHId9y9bXTdO2lOt:-MKefLkH37XNM_AqjYLj:b-ha675h) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L102)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This seems kinda obvious?

I mean, you can have the same condition without threading, e.g. two separate systems publishing to the same subscriber?
</blockquote></details>

Most systems are, by definition, thread-safe. We have a common practice of doing a `Context`-per-thread and reusing the system. As such, the systems that egregiously contradict that workflow should be explicit about that.
___
*[geometry/drake_visualizer.cc, line 170 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeIFXt-7vIzXYSwF20:-MKeitdo3v8Q5e0la2mf:b-uhhuzv) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L170)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit I don't understand what I'm supposed to gain from this comment?

An unrestricted update seems inappropriate for this system? (e.g. `mutable` seems most appropriate, given discussion in #13776)
</blockquote></details>

Done

(It was stale and the code to which it referred had been removed prior to the PR.)
___
*[geometry/drake_visualizer.cc, line 194 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeIdgO-tLoA6bAbfv2:-MKeiou65xYYXMuSDTww:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L194)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This TODO seems stale now?
</blockquote></details>

Done
___
*[geometry/drake_visualizer.cc, line 195 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeIbR59LsqwB51uwKb:-MKeildv9RX98dG19t5Z:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L195)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit spelling "availble"
</blockquote></details>

Done
___
*[geometry/drake_visualizer.cc, line 215 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHfCh5inLpvFul66i:-MKehkMV6fo1geKjjvOi:bqq2m0p) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L215)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

FYI @sammy-tri We had spoken about this before - publicly exposing the message translation so that we could do multi-robot visualization. (#12702)
</blockquote></details>

I saw that conversation, and I'll probably do so when I replace the functionality in `geometry_visualization.{h|cc}`. More particularly, at the time provide the ability to arbitrarily send load and draw messages from a context and lcm.

I'll probably juggle code around, do some deprecation, extend the available feature set all in a follow-up PR.
___
*[geometry/drake_visualizer.cc, line 285 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHofPDJcO6YMAZMjR:-MKehbbS8Qo8TGDG24Iz:b-ordlov) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L285)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This channel is part of the public API (e.g. consumers should expect exactly this channel).

Can you hoist this to a public constant, e.g. `DrakeVisualizer::kLoadMessageChannel`?
</blockquote></details>

See comment below (sorry, I process comments from the bottom up so that I don't pollute the reviewable line numbers).
___
*[geometry/drake_visualizer.cc, line 326 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHylz7drNhrRtIqsU:-MKeg_Tz6ojMdEijv5sX:b-pnf6l5) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L326)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This channel is part of the public API (e.g. consumers should expect exactly this channel).

Can you hoist this to a public constant, e.g. `DrakeVisualizer::kDrawMessageChannel`?
</blockquote></details>

I'm unclear on what problem is being solved here. The class documentation clearly calls out the LCM channel names. The only real utility of making this a public constant would be if some other Drake entity needed access to that value. E.g., implementing a subscriber that runs...in the same process?  A different process?  Or, perhaps, implement another broadcaster that broadcasts to the same channels?
___
*[geometry/test/drake_visualizer_test.cc, line 169 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MK_6RV9-aXdn6bFwtiA:-MKelWE80jlyNU-wPgQV:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/test/drake_visualizer_test.cc#L169)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit s/int/in
</blockquote></details>

Done
___
*[geometry/test/drake_visualizer_test.cc, line 171 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeJBjJ4pzbk9DTGnrN:-MKelNYW5sNEQcLeRrbW:b-2wjrtk) ([raw file](https://github.com/r [...]

2020-10-27 18:14 UTC, EricCousineau-TRI commented
Is it cool if I circle back tomorrow? Playing w/ HW today.

2020-10-27 18:25 UTC, SeanCurtis-TRI reviewed
Absolutely.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247#-:-MKfIbWM3s5bkgRDnQ2x:b-dbzu8r)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI)



<!-- Sent from Reviewable.io -->

2020-10-28 21:22 UTC, EricCousineau-TRI reviewed
> Reviewed 3 of 15 files at r1, 2 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

___
*[geometry/drake_visualizer.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeMPN30g_4puGrKKeG:-MKl3VQT6xHHc10KDOWW:b4uy66e) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L19)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The PR is already huge, I'd rather defer that to the second check box in the linked issue (#13597). Essentially, I think `ConnectDrakeVisualizer` will essentially play that role (for reasons of backwards compatibility).
</blockquote></details>

Disagreed?

You had to change call sites in this PR - if you had just scooped out the innards of `ConnectDrakeVisualizer` and replaced them, then no change would be necessary?
___
*[geometry/drake_visualizer.h, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHHId9y9bXTdO2lOt:-MKl3g28EAGXZZUh2wQ_:b-3fpc1u) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L102)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Most systems are, by definition, thread-safe. We have a common practice of doing a `Context`-per-thread and reusing the system. As such, the systems that egregiously contradict that workflow should be explicit about that.
</blockquote></details>

I mean, this contradicts that workflow without threads even being part of the picture?
e.g. if I connect multiple drake visualizers (with different poses), then I'm gonna get this tearing effect anyways?
___
*[geometry/drake_visualizer.cc, line 215 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHfCh5inLpvFul66i:-MKl3vS_B9CjfE-QkQEC:b-imzn00) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L215)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I saw that conversation, and I'll probably do so when I replace the functionality in `geometry_visualization.{h|cc}`. More particularly, at the time provide the ability to arbitrarily send load and draw messages from a context and lcm.

I'll probably juggle code around, do some deprecation, extend the available feature set all in a follow-up PR.
</blockquote></details>

OK Sweet!!!
___
*[geometry/drake_visualizer.cc, line 285 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHofPDJcO6YMAZMjR:-MKl4QuS1OUooMBMMK8Y:b-1l0aj6) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L285)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

See comment below (sorry, I process comments from the bottom up so that I don't pollute the reviewable line numbers).
</blockquote></details>

OK Will keep just one active discussion.
___
*[geometry/drake_visualizer.cc, line 326 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHylz7drNhrRtIqsU:-MKl4-kJ3qC7LauQaaSc:b8eqgm6) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L326)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm unclear on what problem is being solved here. The class documentation clearly calls out the LCM channel names. The only real utility of making this a public constant would be if some other Drake entity needed access to that value. E.g., implementing a subscriber that runs...in the same process?  A different process?  Or, perhaps, implement another broadcaster that broadcasts to the same channels?
</blockquote></details>

The defect is that misspellings can easily happen with strings, and effectively have silent errors in test code or user code that's being creative.
The pro to a constant is having the public contract violation being *easily* detected via compile-time errors.

(Still, just a nit, so feel free to strictly dismiss)
___
*[geometry/test/drake_visualizer_test.cc, line 171 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeJBjJ4pzbk9DTGnrN:-MKl4XQg2A0_cSKeaX8H:bp5a02z) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/test/drake_visualizer_test.cc#L171)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

(Fixed ints; the styleguide specifically says ["built in types"](https://drake.mit.edu/styleguide/cppguide.html#Variable_and_Array_Initialization), so I'm leaving the structs as is.
</blockquote></details>

Working: I want to confirm that LCM types do not pose an issue if they are not initialized.
I remember running into this before.

(Will find relevant convo, then trace it back to see if it's still an issue.)
___
*[geometry/test/drake_visualizer_test.cc, line 234 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeJQRF6oLSFWEkRy7D:-MKl4hGl50e0cZAeHDxc:bqv35dw) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/test/drake_visualizer_test.cc#L234)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I know what you mean. However, *this* class has the responsibility to take the provided parameter and exercise the correct framework API. It promises to do so. So, in my mind, I have to provide evidence that it has done so. So, this test must exist. I'm open to the argument that it perhaps does more than strictly necessary (e.g., advancing 5 periods may be overkill...two would probably have been enough).
</blockquote></details>

OK Yeah, would be nice to see less code, but I'm fine with it staying as-is.


<!-- Sent from Reviewable.io -->

2020-10-28 21:24 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @SeanCurtis-TRI)

___
*[geometry/test/drake_visualizer_test.cc, line 171 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeJBjJ4pzbk9DTGnrN:-MKl5Ayy7Sy_lA6y1kv8:b-xuoxe6) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/test/drake_visualizer_test.cc#L171)):*
See this discussion item from @jwnimmer-tri:
https://github.com/RobotLocomotion/drake/pull/13311#pullrequestreview-412154537

> nit Must always use value-initialzation (moustache) for lcm type like `Message`; otherwise the local variable is filled with UB-hazardous garbage.


<!-- Sent from Reviewable.io -->

2020-10-28 21:29 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @SeanCurtis-TRI)

___
*[geometry/test/drake_visualizer_test.cc, line 171 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeJBjJ4pzbk9DTGnrN:-MKl5qxM7za2JkQ65ikj:b-4p4wpy) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/test/drake_visualizer_test.cc#L171)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

See this discussion item from @jwnimmer-tri:
https://github.com/RobotLocomotion/drake/pull/13311#pullrequestreview-412154537

> nit Must always use value-initialzation (moustache) for lcm type like `Message`; otherwise the local variable is filled with UB-hazardous garbage.
</blockquote></details>

Also checked generated LCM types; these structures do not have the mustache, and they do not have default ctor.

To see for yourself, open the header generated by this command:
```
$ bazel build //lcmtypes:drake_signal_lcm_library_gen
...
Target //lcmtypes:drake_signal_lcm_library_gen up-to-date:
  bazel-bin/lcmtypes/drake/lcmt_drake_signal.hpp
...
```


<!-- Sent from Reviewable.io -->

2020-10-28 21:32 UTC, EricCousineau-TRI reviewed
> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @SeanCurtis-TRI)

___
*[geometry/drake_visualizer.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeMPN30g_4puGrKKeG:-MKl6jg6C3O-MK16M1Ao:b32ud18) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Disagreed?

You had to change call sites in this PR - if you had just scooped out the innards of `ConnectDrakeVisualizer` and replaced them, then no change would be necessary?
</blockquote></details>

(For the record, I think just changing the implementation is fine for this PR - then a follow-up can expose the new public API / fiddle with deprecation?)

As an aside, changing the underlying structure may break hacky downstream applications that burrow into the diagram or expect a certain implementation.
I am 100% A-OK with that.


<!-- Sent from Reviewable.io -->

2020-10-28 21:50 UTC, EricCousineau-TRI requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with some minor remaining comments / request to replace `ConnectDrakeVisualizer` implementation? (assuming it doesn't break tests within Drake itself)

> Reviewed 2 of 15 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247#-:-MKlB6b5CaWcc06g7FDQ:b-yqlkjx)* status: 12 unresolved discussions, needs at least two assigned reviewers (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @SeanCurtis-TRI)

___
*[geometry/drake_visualizer.h, line 38 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl7At-CG8mUNR2h9EF:-MKl7At-CG8mUNR2h9EG:b7sa6jw) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L38)):*
> ```objc
> };
> 
> /** A system that publishes LCM messages compatible with the `drake_visualizer`
> ```

nit Consider place "(Director)" in parentheses.

FWIW I hate that we've masked the true application's name (Director) with Drake's special sauce (drake visualizer)...
___
*[geometry/drake_visualizer.h, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl7Q9k7TAh0j_qKeZL:-MKl7Q9k7TAh0j_qKeZM:b-2gskjl) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L76)):*
> ```objc
> 
>  The ("phong", "diffuse") generally defines the color of the geometry in
>  `drake_visualizer`. The notable exception is if the geometry is a Mesh which
> ```

The ordering of these last two sentences is confusing; I don't know what's independent / dependent on what.

If it's a Mesh with a .mtl file, then what? Will it ignore the texture (given previous sentence), or will it apply a default color if it's missing, or is the default color only relevant for non-Mesh objects with a missing color property?
___
*[geometry/drake_visualizer.h, line 97 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl7s836_nSb8GbW-SB:-MKl7s836_nSb8GbW-SC:b-h6x0jv) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L97)):*
> ```objc
>  @note If collision geometries are added to SceneGraph by parsing URDF/SDF
>  files, they will not have diffuse values. Even if elements are added to the
>  specification files; it is not currently parsed. They must be added to the
> ```

nit Semi-colon `;` seems out of place here?
___
*[geometry/drake_visualizer.h, line 126 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl85AtEuGz1f29MW-x:-MKl85AtEuGz1f29MW-y:b-hfpsnv) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L126)):*
> ```objc
>   /** Returns the QueryObject-valued input port. It should be connected to
>    SceneGraph's QueryObject-valued output port. Failure to do so will cause a
>    runtime error.  */
> ```

nit When the error occurs should be qualified.

"will cause a runtime error when geometry is initialized or published" or something like that?
___
*[geometry/drake_visualizer.h, line 150 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl8OaA-0fIiIMmGF6M:-MKl8OaA-0fIiIMmGF6N:bh5boi9) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L150)):*
> ```objc
>   struct DynamicFrameData {
>     FrameId frame_id;
>     int num_geometry;
> ```

nit Even though this is internal, can `num_geometry` grow a mustache `{}` too for initialization?
___
*[geometry/drake_visualizer.h, line 169 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl8_IB9Hr5wkUZTEgF:-MKl8_IB9Hr5wkUZTEgG:b-a0ylsw) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L169)):*
> ```objc
>    mutex that will allow updating that model safely. More particularly, we use
>    the mutex to make the entire SendGeometryMessage method atomic; we don't want
>    a load-draw pair of messages to be interrupted.  */
> ```

nit "to be interrupted" implies that there may be some global knowledge (per above point about having multiple disparate `DrakeVisualizer` systems).

Can this be qualified to "to be interrupted by publishes from this object"?
___
*[geometry/drake_visualizer.h, line 181 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl8nfgDQJ0uI0PKFkf:-MKl8nfgDQJ0uI0PKFkg:bgjoqtd) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L181)):*
> ```objc
> 
>   /* The LCM interface: the owned (if such exists) and the work interface
>    (whether owned or not). The work method is mutable because we non-const
> ```

nit "work method" should be "work interface"?
___
*[geometry/test/drake_visualizer_test.cc, line 31 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl9d3b6c_V6rMkpDKt:-MKl9d3cEoTScD9B5kIv:b8c3ymv) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/test/drake_visualizer_test.cc#L31)):*
> ```cpp
> namespace geometry {
> 
> /* Note: We're not using an anonymous namespace so the DrakeVisualizerTest
> ```

BTW It was confusing to see `namespace {` below this comment.

Perhaps better to move it before the declaration of `DrakeVisualizerTest`?
___
*[geometry/test/drake_visualizer_test.cc, line 105 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl9x0z4AI1s2ihCND8:-MKl9x0z4AI1s2ihCND9:b-qk8eyc) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/test/drake_visualizer_test.cc#L105)):*
> ```cpp
>   /* Returns the pointer to the `visualizer`'s active lcm interface -- the one
>    being invoked to do work (can't be nullptr). */
>   static const lcm::DrakeLcmInterface* get_active_interface(
> ```

nit The docstrings in the header file use the term "work interface", but this testing code uses "active interface".

Can one of the two be reconciled?

(FTR I like "active interface" better ;)
___
*[geometry/test/drake_visualizer_test.cc, line 509 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKlAxAf21PRyFxpItY-:-MKlAxAf21PRyFxpItY0:b9qowlv) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/test/drake_visualizer_test.cc#L509)):*
> ```cpp
>     // Negative publish period.
>     EXPECT_THROW(
>         DrakeVisualizer(&lcm_, DrakeVisualizerParams{-0.1, Role::kIllustration,
> ```

BTW Meh on readability for visual indents :(


<!-- Sent from Reviewable.io -->

2020-10-28 22:14 UTC, SeanCurtis-TRI reviewed
See responses.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247#-:-MKlBEtk1F3AlAsBrviY:b-tjeope)* status: 6 unresolved discussions, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[geometry/drake_visualizer.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeMPN30g_4puGrKKeG:-MKl8C8y7J7A6KMIu_YK:b-cuaxrj) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(For the record, I think just changing the implementation is fine for this PR - then a follow-up can expose the new public API / fiddle with deprecation?)

As an aside, changing the underlying structure may break hacky downstream applications that burrow into the diagram or expect a certain implementation.
I am 100% A-OK with that.
</blockquote></details>

I didn't *have* to change call sites. I did to give a concrete example of the new system being exercised.

FTR I've started doing the work, and it is *not trivial*. I'll tag you as feature reviewer when I submit the PR so you can appreciate what's going on. But to give you a glimpse, here's a couple of related issues:

  - Look at the variant of `ConnectDrakeVisualizer` that takes a port for the `PoseBundle`-valued port. That's not a "hide things under the implementation hood" issue, that's a full on API issue. There is no way to implement *that* API with this System.
  - The `ConnectDrakeVisualizer` methods are declared to return a pointer to the `LcmPublisherSystem`. That system type would not be part of the alternate implementation and couldn't be returned.
  - Don't even get me started on `DispatchLoadMessage()`.
___
*[geometry/drake_visualizer.h, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHHId9y9bXTdO2lOt:-MKl8TWv0e8u_m-gietO:b-32s40v) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L102)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I mean, this contradicts that workflow without threads even being part of the picture?
e.g. if I connect multiple drake visualizers (with different poses), then I'm gonna get this tearing effect anyways?
</blockquote></details>

I don't understand your point. You're talking about an adversarial workflow that this comment doesn't even go near.

I've tweaked the language to more directly reflect my intent. The change, I believe, should make the disparity between what I'm trying to say and what it appears you're saying pretty clear.
___
*[geometry/drake_visualizer.h, line 38 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl7At-CG8mUNR2h9EF:-MKlBJ180PAervxkJFYO:bdoegne) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L38)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Consider place "(Director)" in parentheses.

FWIW I hate that we've masked the true application's name (Director) with Drake's special sauce (drake visualizer)...
</blockquote></details>

OK

Given that "Director" doesn't really appear anywhere where Drake users can see, I believe that would only confuse. But I agree with your complaint. Too many names....
___
*[geometry/drake_visualizer.h, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl7Q9k7TAh0j_qKeZL:-MKlEHGMDkBCqDZQtRiF:b2mpacc) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L76)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

The ordering of these last two sentences is confusing; I don't know what's independent / dependent on what.

If it's a Mesh with a .mtl file, then what? Will it ignore the texture (given previous sentence), or will it apply a default color if it's missing, or is the default color only relevant for non-Mesh objects with a missing color property?
</blockquote></details>

I've revamped this whole discussion.  PTAL
___
*[geometry/drake_visualizer.h, line 97 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl7s836_nSb8GbW-SB:-MKlCPnjEOoB0t1_3Xlu:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L97)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Semi-colon `;` seems out of place here?
</blockquote></details>

Done
___
*[geometry/drake_visualizer.h, line 126 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl85AtEuGz1f29MW-x:-MKlCEz87hcVTMdxQch_:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L126)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit When the error occurs should be qualified.

"will cause a runtime error when geometry is initialized or published" or something like that?
</blockquote></details>

Done
___
*[geometry/drake_visualizer.h, line 150 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl8OaA-0fIiIMmGF6M:-MKlC6xi5ODAJd781_pa:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L150)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Even though this is internal, can `num_geometry` grow a mustache `{}` too for initialization?
</blockquote></details>

Done
___
*[geometry/drake_visualizer.h, line 169 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl8_IB9Hr5wkUZTEgF:-MKlBjsG44QHHwYmFvqP:bh6djwc) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L169)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "to be interrupted" implies that there may be some global knowledge (per above point about having multiple disparate `DrakeVisualizer` systems).

Can this be qualified to "to be interrupted by publishes from this object"?
</blockquote></details>

This is further proof that we were having different conversations. See my clarification on thread safety above and why this comment has nothing to do with that.

That said, I can't tell if you're looking for a warning about the inadvisability of attaching multiple instances of `DrakeVisualizer` with a shared `DrakeLcmInterface` to a single `Diagram` -- that's the issue you really seem to be focused on.
___
*[geometry/drake_visualizer.h, line 181 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl8nfgDQJ0uI0PKFkf:-MKlBgHw-7FiWNKNDA5v:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L181)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit "work method" should be "work interface"?
</blockquote></details>

Done
___
*[geometry/drake_visualizer.cc, line 326 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHylz7drNhrRtIqsU:-MKl8lfyAzM_rrXc-xRq:b-vi747s) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L326)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

The defect is that misspellings can easily happen with strings, and effectively have silent errors in test code or user code that's being creative.
The pro to a const [...]

2020-10-28 22:38 UTC, EricCousineau-TRI reviewed
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: needs at least two assigned reviewers

___
*[geometry/drake_visualizer.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeMPN30g_4puGrKKeG:-MKlJrdFBgen67P1Nq3S:b-52z8c0) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L19)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I didn't *have* to change call sites. I did to give a concrete example of the new system being exercised.

FTR I've started doing the work, and it is *not trivial*. I'll tag you as feature reviewer when I submit the PR so you can appreciate what's going on. But to give you a glimpse, here's a couple of related issues:

  - Look at the variant of `ConnectDrakeVisualizer` that takes a port for the `PoseBundle`-valued port. That's not a "hide things under the implementation hood" issue, that's a full on API issue. There is no way to implement *that* API with this System.
  - The `ConnectDrakeVisualizer` methods are declared to return a pointer to the `LcmPublisherSystem`. That system type would not be part of the alternate implementation and couldn't be returned.
  - Don't even get me started on `DispatchLoadMessage()`.
</blockquote></details>

OK Ah, totes sold on the non-trivial bit... forgot about port types :facepalm: 

Thanks!
___
*[geometry/drake_visualizer.h, line 102 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHHId9y9bXTdO2lOt:-MKlKCmC07eIS4y8HUUw:b38pc6d) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L102)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I don't understand your point. You're talking about an adversarial workflow that this comment doesn't even go near.

I've tweaked the language to more directly reflect my intent. The change, I believe, should make the disparity between what I'm trying to say and what it appears you're saying pretty clear.
</blockquote></details>

OK Will redact given that it's now constrained to a single-instance (assumed with different contexts). Thanks!
___
*[geometry/drake_visualizer.h, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl7Q9k7TAh0j_qKeZL:-MKlK7oV04Aij4cjA7Ij:b-w196av) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L76)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I've revamped this whole discussion.  PTAL
</blockquote></details>

OK Thanks!
___
*[geometry/drake_visualizer.h, line 169 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl8_IB9Hr5wkUZTEgF:-MKlKcXa41GCf6qBjlmn:b-mxbfbd) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L169)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

This is further proof that we were having different conversations. See my clarification on thread safety above and why this comment has nothing to do with that.

That said, I can't tell if you're looking for a warning about the inadvisability of attaching multiple instances of `DrakeVisualizer` with a shared `DrakeLcmInterface` to a single `Diagram` -- that's the issue you really seem to be focused on.
</blockquote></details>

OK Yup! Sorry, the multi-instance was what I more-or-less thought you were implying.

An explicit call-out, like "It is inadvisable to have multiple instances in the same diagram (ultimately publishing to the same channels)." would work, but won't block on it.
___
*[geometry/drake_visualizer.cc, line 326 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHylz7drNhrRtIqsU:-MKlL-FUDAiWFrr7dCoj:br35dfr) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L326)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'm still not clear *which code* is supposed to be typing this string that would also have access to such a public API. Can you describe some realistic code you'd write where this would be an issue?

And, in fact, if I were *really* going to expose it, I would actually add it to the params with these strings as default values, so people would have equal ability to change the channel name as find it out from a default-instantiated param set. But I'm deferring doing it, because that would solve a problem that hasn't appeared yet.
</blockquote></details>

OK I was thinking there were more instances of code that uses it. I now see that I've over-inflated it:
```
$ cd /path/to/drake
$ grep -rnI -l 'DRAKE_VIEWER_.*'
geometry/geometry_visualization.cc
geometry/geometry_visualization.h
tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_time.py
bindings/pydrake/test/geometry_test.py
bindings/pydrake/systems/planar_scenegraph_visualizer.py
bindings/pydrake/systems/meshcat_visualizer.py

$ cd /path/to/anzu
$ grep -rnI '"DRAKE_VIEWER_.*"' | wc -l
8
```

So there was realistic code where this was written, but it's probably not a big deal to fix it for these usages. (Only a few in Drake are outside of `//geometry`, and they seem, uh, hacky enough to not warrant a fix for them)


<!-- Sent from Reviewable.io -->

2020-10-28 22:45 UTC, SeanCurtis-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: needs at least two assigned reviewers

___
*[geometry/drake_visualizer.h, line 19 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeMPN30g_4puGrKKeG:-MKlNTj-DISsuL1Fp-RG:bwhouhr) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.h#L19)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Ah, totes sold on the non-trivial bit... forgot about port types :facepalm: 

Thanks!
</blockquote></details>

(No worries...I thought it would be easy until I started doing it.)
___
*[geometry/drake_visualizer.h, line 169 at r2](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKl8_IB9Hr5wkUZTEgF:-MKlNalm2KzayzqVUwUo:bu71o40) ([raw file](https://github.com/robotlocomotion/drake/blob/572e0f093bfc016b1881cf7876aa3a022769d1f2/geometry/drake_visualizer.h#L169)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Yup! Sorry, the multi-instance was what I more-or-less thought you were implying.

An explicit call-out, like "It is inadvisable to have multiple instances in the same diagram (ultimately publishing to the same channels)." would work, but won't block on it.
</blockquote></details>

OK I'm going to defer that just to get this moving forward.
___
*[geometry/drake_visualizer.cc, line 326 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeHylz7drNhrRtIqsU:-MKlNgBP62k783emtN4c:bhn9yp3) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/drake_visualizer.cc#L326)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK I was thinking there were more instances of code that uses it. I now see that I've over-inflated it:
```
$ cd /path/to/drake
$ grep -rnI -l 'DRAKE_VIEWER_.*'
geometry/geometry_visualization.cc
geometry/geometry_visualization.h
tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_time.py
bindings/pydrake/test/geometry_test.py
bindings/pydrake/systems/planar_scenegraph_visualizer.py
bindings/pydrake/systems/meshcat_visualizer.py

$ cd /path/to/anzu
$ grep -rnI '"DRAKE_VIEWER_.*"' | wc -l
8
```

So there was realistic code where this was written, but it's probably not a big deal to fix it for these usages. (Only a few in Drake are outside of `//geometry`, and they seem, uh, hacky enough to not warrant a fix for them)
</blockquote></details>

And most of those will completely evaporate.  :)


<!-- Sent from Reviewable.io -->

2020-10-28 22:46 UTC, SeanCurtis-TRI reviewed
+@jwnimmer-tri for platform review (end of day Wednesday pushes this to Thursday).

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247#-:-MKlNr-cEAv_scGxG-cV:b-bb2d9x)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)



<!-- Sent from Reviewable.io -->

2020-10-29 05:24 UTC, jwnimmer-tri reviewed
> Reviewed 9 of 15 files at r1, 4 of 5 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: 16 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @SeanCurtis-TRI)

___
*[geometry/BUILD.bazel, line 80 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmWd946VocYx--3tIg:-MKmWd946VocYx--3tIh:b-4dubo4) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/BUILD.bazel#L80)):*
> ```Starlark
>         "//lcmtypes:viewer",
>         "//systems/framework:context",
>         "//systems/framework:event_collection",
> ```

nit ":event_collection" seems unused.
___
*[geometry/drake_visualizer.h, line 114 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmY-VhAOczp_vcTnH_:-MKmY-VhAOczp_vcTnHa:b-v526xl) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/drake_visualizer.h#L114)):*
> ```objc
> 
>    @param lcm     An optional LCM interface. If none is provided, this system
>                   will own its own instance. If one is provided it must remain
> ```

nit Consider s/own/allocate/ for the first "own".  It's more specific, and the "own own" repetition was awkward.
___
*[geometry/drake_visualizer.h, line 170 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmYW0hDsmBiJ91GaEo:-MKmYW0hDsmBiJ91GaEp:b-ue1srm) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/drake_visualizer.h#L170)):*
> ```objc
>    a load-draw pair of messages to be interrupted.  */
> 
>   /* The version of the geometry that was last loaded (i.e.., had a load message
> ```

nit Typo "..".
___
*[geometry/drake_visualizer.h, line 183 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmYtHt1g-TB9dtVWk_:-MKmYtHt1g-TB9dtVWka:bao11b5) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/drake_visualizer.h#L183)):*
> ```objc
>    access to the LCM interface in const System methods.  */
>   std::unique_ptr<lcm::DrakeLcmInterface> owned_lcm_{};
>   mutable lcm::DrakeLcmInterface* lcm_;
> ```

nit Pointer (non-const POD) `lcm_` needs moustache.
___
*[geometry/drake_visualizer.cc, line 27 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmg9F89trJPSj3MqSm:-MKmg9F89trJPSj3MqSn:bw6tcxk) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/drake_visualizer.cc#L27)):*
> ```cpp
> using systems::EventStatus;
> using systems::State;
> using systems::UnrestrictedUpdateEvent;
> ```

nit Unused EventStatus, UnrestrictedUpdateEvent, State, ...
___
*[geometry/drake_visualizer.cc, line 188 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmaRr1DQWKocZoUxYf:-MKmaRr1DQWKocZoUxYg:b-d3zuwo) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/drake_visualizer.cc#L188)):*
> ```cpp
> void DrakeVisualizer::SendGeometryMessage(
>     const Context<double>& context) const {
>   std::lock_guard<std::mutex> lock(mutex_);
> ```

I'd like to push back on the idea of trying to hold the lock for the entire method (as seen below, and commented on in the header), for a few reasons.

(1) In general, is it is bad juju to hold a lock and then call into other code.  If that code ends up trying to take other locks (or retake this lock), that can lead to deadlock / priority inversion / etc. race conditions that are _extremely_ difficult to debug.

(2) The hypothesis does not hold that by carefully transmitting load+draw pairs under the lock we can make a claim about what the drake_visualizer displays.  Message order is not deterministic, and message delivery is not guaranteed.  If there _was_ contention for this lock, there is every chance that the messages get mixed up on the receiving end anyway.

The simple answer is that only the read+write of the `version_` should be guarded by the lock:
```c++
const auto& query_object = ...;
const GeometryVersion& current_version = ...;
bool send_load_message = false;
{
  std::lock_guard<std::mutex> lock(mutex_);
  if (!version_.IsSameAs(current_version, params_.role) {
    needs_load = true;
    version_ = current_version;
  }
}
if (send_load_message) {
  SendLoadMessage(...);
}
SendPoseMessage(...);
```
___
*[geometry/drake_visualizer.cc, line 198 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmdE6A-WPfcinIIwu2:-MKmdE6A-WPfcinIIwu3:b-x2xu3m) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/drake_visualizer.cc#L198)):*
> ```cpp
>     get_cache_entry(dynamic_data_cache_index_)
>         .get_mutable_cache_entry_value(context)
>         .mark_out_of_date();
> ```

nit It seems to me calling `SendLoadMessage` without preceding it by this `mark_out_of_date` would _always_ be incorrect.  That suggests that this statement should live within `SendLoadMessage` for robustness.
___
*[geometry/drake_visualizer.cc, line 253 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmewp-5HAfgtOk0KVg:-MKmewp-5HAfgtOk0KVh:b-9rijv) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/drake_visualizer.cc#L253)):*
> ```cpp
>     message.link[0].num_geom = anchored_count;
>     message.link[0].geom.resize(anchored_count);
>     int geom_index = -1;  // we'll pre-increment before using.
> ```

nit Cap "We".

Ditto below.
___
*[geometry/drake_visualizer.cc, line 283 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmfFWM9DlknvcQ6hKS:-MKmfFWN9A-fNWwCBbFm:bjt6y74) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/drake_visualizer.cc#L283)):*
> ```cpp
>   const SceneGraphInspector<double>& inspector = query_object.inspector();
> 
>   lcmt_viewer_draw message;
> ```

nit Use `{}` to guarantee that we don't leave any garbage in the message.
___
*[geometry/geometry_version.h, line 53 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmnkiSBeDf9CWygbgy:-MKmnkiTDBiDBafuvk4S:b-difdfb) ([raw file](https://github.com/robotlocomotion/drake/blob/81aebc7a2b10e8bb5cf331b1a89e6d3a67d05070/geometry/geometry_version.h#L53)):*
> ```objc
>   /* Create unique version id for all roles so that the new geometry version
>    unique. */
>   GeometryVersion();
> ```

FYI This is a good lesson that gratuitously locking down APIs is a maintenance burden.  It was unreasonable in the first place to have this constructor and the mutators below marked as private.  There is no useful invariant to protect here.  They should have been public from the get-go.
___
*[geometry/scene_graph_inspector.h, line 375 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmVAVr4RON6ilgvwB5:-MKmVAVr4RON6ilgvwB6:b-689mg5) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/scene_graph_inspector.h#L375)):*
> ```objc
>       case Role::kPerception:
>         return state_->GetPerceptionProperties(geometry_id);
>       default:
> ```

nit Don't use "default" in switches -- it defeats the compiler warning pointing to required modifications when we add a new role type.
___
*[geometry/test/drake_visualizer_test.cc, line 171 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeJBjJ4pzbk9DTGnrN:-MKmRUJ687Wonur0RXzJ:b-3c0fl9) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/test/drake_visualizer_test.cc#L171)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

Given how strongly @jwnimmer-tri put that, we have a defect somewhere that it can't be inferred from the code in question and the styleguide.
</blockquote></details>
 [...]

2020-10-29 16:30 UTC, SeanCurtis-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[geometry/drake_visualizer.cc, line 27 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmg9F89trJPSj3MqSm:-MKp5Jeg3VH9Oz_XNUhP:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/drake_visualizer.cc#L27)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unused EventStatus, UnrestrictedUpdateEvent, State, ...
</blockquote></details>

Done
___
*[geometry/drake_visualizer.cc, line 188 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmaRr1DQWKocZoUxYf:-MKp0E-A2kdYguFmcpR5:b5r1mv4) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/drake_visualizer.cc#L188)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I'd like to push back on the idea of trying to hold the lock for the entire method (as seen below, and commented on in the header), for a few reasons.

(1) In general, is it is bad juju to hold a lock and then call into other code.  If that code ends up trying to take other locks (or retake this lock), that can lead to deadlock / priority inversion / etc. race conditions that are _extremely_ difficult to debug.

(2) The hypothesis does not hold that by carefully transmitting load+draw pairs under the lock we can make a claim about what the drake_visualizer displays.  Message order is not deterministic, and message delivery is not guaranteed.  If there _was_ contention for this lock, there is every chance that the messages get mixed up on the receiving end anyway.

The simple answer is that only the read+write of the `version_` should be guarded by the lock:
```c++
const auto& query_object = ...;
const GeometryVersion& current_version = ...;
bool send_load_message = false;
{
  std::lock_guard<std::mutex> lock(mutex_);
  if (!version_.IsSameAs(current_version, params_.role) {
    needs_load = true;
    version_ = current_version;
  }
}
if (send_load_message) {
  SendLoadMessage(...);
}
SendPoseMessage(...);
```
</blockquote></details>

Done

I certainly felt uneasy on number 1 and, as such, am easily persuaded against it. And your argument about number 2 is excellent; `DrakeVisualizer`'s best efforts to "guarantee" coherency are insufficient. So, why bend over backwards?

That does raise the question of the *value* of protecting the version test from race conditions. Some thoughts:

1. Imagine a situation where the locked code decides that a send message is required. But between that decision and the process of sending the message, the version changes again; the basis for the decision is no longer in sync with the action. This seems alright. Because either the version has been restored to its original case in which case we'll simply send a redundant load message. Or it'll be advanced to yet another version, which will still need to be sent (and then a subsequent load will be sent in a later iteration). Not a unique problem.
2. I'm ignoring the case where the context itself is actually provided to multiple threads (with write access). I've changed the documentation to particularly call that out as a strictly bad thing.

But what does this gain us? What would the implications be of a race condition that we didn't protect against?

1. The test says "need update", but then the cached version changes between that determination and writing the version. That seems just like the case outlined above in 1.
2. The test says don't need update, but then the version changes before we send the pose message. That's no different from interleaved send/draws where the state of the visualizer doesn't match our best guess. We've already decided we can't make any guarantees in that regard. So, avoiding this race condition doesn't help.

I'm leaving the mutex in as you suggest, but, ultimately, I'm walking away with a sense of....meh. Why bother?
___
*[geometry/drake_visualizer.cc, line 198 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmdE6A-WPfcinIIwu2:-MKp04TB4ViEdcbqRS3u:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/drake_visualizer.cc#L198)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit It seems to me calling `SendLoadMessage` without preceding it by this `mark_out_of_date` would _always_ be incorrect.  That suggests that this statement should live within `SendLoadMessage` for robustness.
</blockquote></details>

Done
___
*[geometry/geometry_version.h, line 53 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmnkiSBeDf9CWygbgy:-MKp5R-m55gwFBH_VcS-:b-plekf9) ([raw file](https://github.com/robotlocomotion/drake/blob/81aebc7a2b10e8bb5cf331b1a89e6d3a67d05070/geometry/geometry_version.h#L53)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI This is a good lesson that gratuitously locking down APIs is a maintenance burden.  It was unreasonable in the first place to have this constructor and the mutators below marked as private.  There is no useful invariant to protect here.  They should have been public from the get-go.
</blockquote></details>

Agreed. A relic left over from when it was "more complex" to really tell if two versions were equivalent.
___
*[geometry/scene_graph_inspector.h, line 375 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmVAVr4RON6ilgvwB5:-MKp5iVc0ZRjguvxgl3R:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/scene_graph_inspector.h#L375)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Don't use "default" in switches -- it defeats the compiler warning pointing to required modifications when we add a new role type.
</blockquote></details>

Done
___
*[geometry/test/drake_visualizer_test.cc, line 171 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeJBjJ4pzbk9DTGnrN:-MKp6elzCyCOnq4sbTjx:b-kpq34d) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/test/drake_visualizer_test.cc#L171)):*
> being aware that lcmtypes...remain uninitialized by default.

I guess, not playing with lcm much, I wasn't privy to the tribal knowledge. I grant that lcm and Eigen are analogous in terms of that characteristic. And yet,  Eigens get explicitly called out in the styleguide, but lcm doesn't.
___
*[geometry/test/drake_visualizer_test.cc, line 234 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeJQRF6oLSFWEkRy7D:-MKp6Ot8ALsGXuW4Spl_:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/test/drake_visualizer_test.cc#L234)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I would also like to see the 0.999 and 1.0001 die.  A test at zero makes sense.  Proving that 5*period ==> 5 makes sense.  Anything in the middle is overkill.  This unit test file is already astonishingly long.
</blockquote></details>

Done
___
*[geometry/test/drake_visualizer_test.cc, line 89 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmi8Up4VQU_yaXWA41:-MKp7FSVBC6vMnU6FDF0:b-tlutvr) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/test/drake_visualizer_test.cc#L89)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

What is the purpose of this `unsetenv` line?  Our bazel.rc specifically sets LCM_DEFAULT_URL so as to avoid network traffic while running tests. [...]

2020-10-29 16:32 UTC, SeanCurtis-TRI reviewed
As ever, thanks for the excellent comments.  Couple of discussions remaining.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247#-:-MKpC34B7HLzMrOBjdzj:bq89xxg)* status: 4 unresolved discussions, LGTM missing from assignee jwnimmer-tri(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)



<!-- Sent from Reviewable.io -->

2020-10-29 17:00 UTC, jwnimmer-tri reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247#-:-MKpIRuG-05bjTh8A-vi:bnfp4nl)* status: 3 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[geometry/drake_visualizer.h, line 110 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKpEP5D2qnQsCtPkEc9:-MKpEP5D2qnQsCtPkEcA:b-rglm3t) ([raw file](https://github.com/robotlocomotion/drake/blob/69055f277083f357e640a3c1cd70143ee8d5290c/geometry/drake_visualizer.h#L110)):*
> ```objc
>  It should be emphasized, that sharing a *single* systems::Context instance
>  across multiple threads is *strongly* discouraged and can lead to catastrophic
>  failure.  */
> ```

nit This last sentence is a bit overly restrictive -- it is possible (and used in practice) when the context is frozen (i.e., is not being simulated).

Overall, a shorter replacement for this _entire_ h3 section might be:

"""As with any System that publishes LCM messages, simulating multiple instances of it will lead to multiple messages transmitted on the same channel.  In the case of drake_vizualizer, the multiple visualizations will compete for the one display, which is probably not be what you want."""

It's really not even about threading at all.  Having two copies of this System in the same (single-threaded) Simulator could also be bad.  (For example, if we also had two plants, two SceneGraphs, etc.)
___
*[geometry/drake_visualizer.cc, line 188 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmaRr1DQWKocZoUxYf:-MKpCsc20bv17BuwVePI:bhjopvx) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/drake_visualizer.cc#L188)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Done

I certainly felt uneasy on number 1 and, as such, am easily persuaded against it. And your argument about number 2 is excellent; `DrakeVisualizer`'s best efforts to "guarantee" coherency are insufficient. So, why bend over backwards?

That does raise the question of the *value* of protecting the version test from race conditions. Some thoughts:

1. Imagine a situation where the locked code decides that a send message is required. But between that decision and the process of sending the message, the version changes again; the basis for the decision is no longer in sync with the action. This seems alright. Because either the version has been restored to its original case in which case we'll simply send a redundant load message. Or it'll be advanced to yet another version, which will still need to be sent (and then a subsequent load will be sent in a later iteration). Not a unique problem.
2. I'm ignoring the case where the context itself is actually provided to multiple threads (with write access). I've changed the documentation to particularly call that out as a strictly bad thing.

But what does this gain us? What would the implications be of a race condition that we didn't protect against?

1. The test says "need update", but then the cached version changes between that determination and writing the version. That seems just like the case outlined above in 1.
2. The test says don't need update, but then the version changes before we send the pose message. That's no different from interleaved send/draws where the state of the visualizer doesn't match our best guess. We've already decided we can't make any guarantees in that regard. So, avoiding this race condition doesn't help.

I'm leaving the mutex in as you suggest, but, ultimately, I'm walking away with a sense of....meh. Why bother?
</blockquote></details>

In general, when accessing the same memory from multiple threads, the baseline should be to guard it with a lock.  Even if you _think_ that concurrently editing it would be safe because it's basically just a few PODs, it's way too easy to stumble into UB.
___
*[geometry/test/drake_visualizer_test.cc, line 171 at r1](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKeJBjJ4pzbk9DTGnrN:-MKpCPXFBZLcgptrkaUH:b-za6zmc) ([raw file](https://github.com/robotlocomotion/drake/blob/b06444b48de34c50b64ea22bccb4635ad21a0eb3/geometry/test/drake_visualizer_test.cc#L171)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

> being aware that lcmtypes...remain uninitialized by default.

I guess, not playing with lcm much, I wasn't privy to the tribal knowledge. I grant that lcm and Eigen are analogous in terms of that characteristic. And yet,  Eigens get explicitly called out in the styleguide, but lcm doesn't.
</blockquote></details>

Ah, yes, adding an analogous tip to the Eigen advice in the same list would make sense.
___
*[geometry/test/drake_visualizer_test.cc, line 239 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmjzmU4Dg9rZEnwekI:-MKpHHGC6iTT5wa-Iyb4:b-wotlb6) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/test/drake_visualizer_test.cc#L239)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Don't know. Don't care. I figure if I care about the conditions of my test, I'm responsible for setting them. And since, I do an `AdvanceTo(0.0)`, that pre-condition matters.
</blockquote></details>

This is line of code is confusing, as a reader.  If there's a reason for doing something out of the ordinary, then it needs an comment explaining the situation -- otherwise, it leaves a reader wondering what they have missed.  If there is no reason for a line of code to exist, it should be removed.
___
*[geometry/test/drake_visualizer_test.cc, line 497 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmmZqc3UEzbwnS53I0:-MKpI4f26U-6CsGIiOhn:b-p7o1lf) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/test/drake_visualizer_test.cc#L497)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I'd interpreted the use of `@pre` as not requiring code or tests. But I don't know that I subscribe to the argument that it precludes it.
</blockquote></details>

I don't think that _any_ code gets to violate the documented precondition of a method, even tests.


<!-- Sent from Reviewable.io -->

2020-10-29 17:25 UTC, SeanCurtis-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: 3 unresolved discussions (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[geometry/test/drake_visualizer_test.cc, line 497 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmmZqc3UEzbwnS53I0:-MKpNkdY-KHpjz-AeNHr:b219ptn) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/test/drake_visualizer_test.cc#L497)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think that _any_ code gets to violate the documented precondition of a method, even tests.
</blockquote></details>

If I have code that throws an exception, and I don't exercise that in a unit test, I have an uncovered code path. So, perhaps the error is throwing an exception in response to a documented precondition?


<!-- Sent from Reviewable.io -->

2020-10-29 17:28 UTC, jwnimmer-tri reviewed
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: 3 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[geometry/test/drake_visualizer_test.cc, line 497 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmmZqc3UEzbwnS53I0:-MKpOPSq4LlCfiBUwoAt:b-a5aabm) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/test/drake_visualizer_test.cc#L497)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

If I have code that throws an exception, and I don't exercise that in a unit test, I have an uncovered code path. So, perhaps the error is throwing an exception in response to a documented precondition?
</blockquote></details>

Right, hand-crafting nice exception messages for `@pre` is unusual, and leads to that problem.

Here I'd advocate for eschewing `@pre` (and, really, all cases that are not inner loops) and keeping the nice messages, but changing to DRAKE_THROW_UNLESS is another valid resolution.


<!-- Sent from Reviewable.io -->

2020-10-29 18:39 UTC, SeanCurtis-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: 3 unresolved discussions (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[geometry/drake_visualizer.h, line 110 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKpEP5D2qnQsCtPkEc9:-MKpPgGA1mY-RxdiV8ZD:b-hc3hom) ([raw file](https://github.com/robotlocomotion/drake/blob/69055f277083f357e640a3c1cd70143ee8d5290c/geometry/drake_visualizer.h#L110)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit This last sentence is a bit overly restrictive -- it is possible (and used in practice) when the context is frozen (i.e., is not being simulated).

Overall, a shorter replacement for this _entire_ h3 section might be:

"""As with any System that publishes LCM messages, simulating multiple instances of it will lead to multiple messages transmitted on the same channel.  In the case of drake_vizualizer, the multiple visualizations will compete for the one display, which is probably not be what you want."""

It's really not even about threading at all.  Having two copies of this System in the same (single-threaded) Simulator could also be bad.  (For example, if we also had two plants, two SceneGraphs, etc.)
</blockquote></details>

Maybe. The word "copy" in your last paragraph is important.  I could easily imagine having two instances configured differently (i.e., via a different `DrakeLcmInterface` instance, visualizing different roles, different properties, whatever). In that case, there would be no error in having two instances.

It seems that any distillation of this conversation to something simple intrinsically leaves out nuances that *someone* will be sensitive to.

The fundamental problem is sending out incoherent messages on a single drake interface. This can happen via:

  - Evaluating a single instance across multiple threads.
  - Evaluating multiple instances which share a single lcm interface.

How do you feel about me spinning it in that direction?


<!-- Sent from Reviewable.io -->

2020-10-29 18:46 UTC, jwnimmer-tri reviewed
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: 3 unresolved discussions (waiting on @SeanCurtis-TRI)

___
*[geometry/drake_visualizer.h, line 110 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKpEP5D2qnQsCtPkEc9:-MKpeH1r7rRUGNI1wKAk:b33rsxf) ([raw file](https://github.com/robotlocomotion/drake/blob/69055f277083f357e640a3c1cd70143ee8d5290c/geometry/drake_visualizer.h#L110)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Maybe. The word "copy" in your last paragraph is important.  I could easily imagine having two instances configured differently (i.e., via a different `DrakeLcmInterface` instance, visualizing different roles, different properties, whatever). In that case, there would be no error in having two instances.

It seems that any distillation of this conversation to something simple intrinsically leaves out nuances that *someone* will be sensitive to.

The fundamental problem is sending out incoherent messages on a single drake interface. This can happen via:

  - Evaluating a single instance across multiple threads.
  - Evaluating multiple instances which share a single lcm interface.

How do you feel about me spinning it in that direction?
</blockquote></details>

If you're asking me if I were in charge, then I'd punt this entire h3.  I don't think it's adding any value, certainly not any value that approaches the mental complexity it takes to parse it.  Instead of trying to do a case analysis on the tx side here, what if we explain the rx side instead?  Something like "Reminder: the drake_visualizer program only supports a single source sending it messages."  Everything else is an obvious conclusion that follows from that fact.  We don't need to walk through all of the ways that people could end up with multiple message senders, do we?


<!-- Sent from Reviewable.io -->

2020-10-29 18:47 UTC, SeanCurtis-TRI reviewed
I think we're in the home stretch.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247#-:-MKpf_L66c9m7a_1qCdF:b-998p6q)* status: 3 unresolved discussions (waiting on @jwnimmer-tri)

___
*[geometry/drake_visualizer.h, line 110 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKpEP5D2qnQsCtPkEc9:-MKpfPBODlr1pt6Vl4xD:b-5dax3u) ([raw file](https://github.com/robotlocomotion/drake/blob/69055f277083f357e640a3c1cd70143ee8d5290c/geometry/drake_visualizer.h#L110)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

If you're asking me if I were in charge, then I'd punt this entire h3.  I don't think it's adding any value, certainly not any value that approaches the mental complexity it takes to parse it.  Instead of trying to do a case analysis on the tx side here, what if we explain the rx side instead?  Something like "Reminder: the drake_visualizer program only supports a single source sending it messages."  Everything else is an obvious conclusion that follows from that fact.  We don't need to walk through all of the ways that people could end up with multiple message senders, do we?
</blockquote></details>

The word "obvious" will always be the contentious judgment. PTAL at my last pass.
___
*[geometry/test/drake_visualizer_test.cc, line 239 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmjzmU4Dg9rZEnwekI:-MKpeKBM4wtiHuHHVGBT:bb6un1j) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/test/drake_visualizer_test.cc#L239)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This is line of code is confusing, as a reader.  If there's a reason for doing something out of the ordinary, then it needs an comment explaining the situation -- otherwise, it leaves a reader wondering what they have missed.  If there is no reason for a line of code to exist, it should be removed.
</blockquote></details>

Done
___
*[geometry/test/drake_visualizer_test.cc, line 497 at r3](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKmmZqc3UEzbwnS53I0:-MKpeLY76b5wV-AvDjN-:bxtf7wn) ([raw file](https://github.com/robotlocomotion/drake/blob/5152830945c42c63b786f057e78bd3d6d37911eb/geometry/test/drake_visualizer_test.cc#L497)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Right, hand-crafting nice exception messages for `@pre` is unusual, and leads to that problem.

Here I'd advocate for eschewing `@pre` (and, really, all cases that are not inner loops) and keeping the nice messages, but changing to DRAKE_THROW_UNLESS is another valid resolution.
</blockquote></details>

Done I've opted to call a spade a spade.


<!-- Sent from Reviewable.io -->

2020-10-29 18:51 UTC, jwnimmer-tri reviewed
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/drake/14247)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),EricCousineau-TRI(platform)

___
*[geometry/drake_visualizer.h, line 110 at r4](https://reviewable.io/reviews/robotlocomotion/drake/14247#-MKpEP5D2qnQsCtPkEc9:-MKpgVnJ0VcbMRBtk1_Z:bfx0nj3) ([raw file](https://github.com/robotlocomotion/drake/blob/69055f277083f357e640a3c1cd70143ee8d5290c/geometry/drake_visualizer.h#L110)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

The word "obvious" will always be the contentious judgment. PTAL at my last pass.
</blockquote></details>

OK This is sufficient.  Once we can customize the URL, we'll probably want advice for how to keep two concurrent-but-distinct visualizations going at once, but that's for another day.


<!-- Sent from Reviewable.io -->

2020-10-29 19:30 UTC, merged